library(dplyr)
library(data.table)
library(plyr)
library(ggplot2)
library(shiny)
library(DT)

#data cleaning
restaurant<-data.frame(fread('NYres.csv'))
summary(restaurant)
restaurant$DBA<-factor(restaurant$DBA)
restaurant$BORO<-factor(restaurant$BORO)
restaurant$BUILDING<-factor(restaurant$BUILDING)
restaurant$STREET<-factor(restaurant$STREET)
restaurant$ZIPCODE<-factor(restaurant$ZIPCODE)
restaurant$PHONE<-factor(restaurant$PHONE)
restaurant$CUISINE.DESCRIPTION<-factor(restaurant$CUISINE.DESCRIPTION)
restaurant$INSPECTION.DATE<-as.Date(restaurant$INSPECTION.DATE,format='%m/%d/%Y')
restaurant$ACTION<-factor(restaurant$ACTION)
restaurant$VIOLATION.CODE<-factor(restaurant$VIOLATION.CODE)
restaurant$VIOLATION.DESCRIPTION<-factor(restaurant$VIOLATION.DESCRIPTION)
restaurant$CRITICAL.FLAG<-factor(restaurant$CRITICAL.FLAG)
restaurant$ GRADE<-factor(restaurant$ GRADE)
restaurant$INSPECTION.TYPE<-factor(restaurant$INSPECTION.TYPE)
restaurant$GRADE.DATE<-as.Date(restaurant$GRADE.DATE,format='%m/%d/%Y')
restaurant$RECORD.DATE<-as.Date(restaurant$RECORD.DATE,format='%m/%d/%Y')

#define restaurant2
restaurant$Address<-paste0(restaurant$BUILDING,' ',restaurant$STREET)
restaurant2<-data.frame(restaurant$DBA,restaurant$Address,restaurant$ZIPCODE,restaurant$BORO,restaurant$PHONE,restaurant$CUISINE.DESCRIPTION)
restaurant2<-unique(restaurant2)
colnames(restaurant2) <- c("Name", "Address","Zipcode","Borough","Phone","Description")
